[package]
name = "rewind-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.11.3"
futures = "0.3.30"
log = "0.4.22"
wgpu = "0.20.1"
winit = { version = "0.30.3", features = ["rwh_06"] }
